big test revamp
Signed-off-by: clux <sszynrae@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,29 +42,25 @@ jobs:
       - name: Build workspace
         run: cargo build
 
-      # Workspace tests
-      - name: Run workspace unit tests
-        run: cargo test --lib --all -j6
+      # Workspace unit tests with various feature sets
+      - name: Run workspace unit tests (no default features)
+        run: cargo test --workspace --lib --no-default-features -j6
+      - name: Run workspace unit tests (default features)
+        run: cargo test --workspace --lib --all --exclude kube-examples --exclude e2e
+      - name: Run workspace unit tests (all features)
+        run: cargo test --workspace --lib --all-features --exclude kube-examples --exclude e2e
+      # Workspace documentation (all features only)
       - name: Run workspace doc tests
-        run: cargo test --doc --all -j6
+        run: cargo test --workspace --doc --all-features --exclude kube-examples --exclude e2e -j6
+      - name: Doc test verification (should never be ignored)
+        run: |
+          if rg "\`\`\`ignored"; then
+            echo "ignored doctests are not allowed, use compile_fail or no_run"
+            exit 1
+          fi
+      # Examples
       - name: Test examples
         run: cargo test -p kube-examples --examples -j6
-      - name: Compile check remaining examples
-        # No OS specific code in examples, run this on fastest executor
-        if: matrix.os == 'ubuntu-latest'
-        run: cargo build -j4 -p kube-examples
-
-      # Feature tests
-      - name: Test kube with features rustls-tls,ws,oauth
-        run: cargo test -p kube --lib --no-default-features --features=rustls-tls,ws,oauth
-        if: matrix.os == 'ubuntu-latest'
-      - name: Test kube with features openssl-tls,ws,oauth
-        run: cargo test -p kube --lib --no-default-features --features=openssl-tls,ws,oauth
-        if: matrix.os == 'ubuntu-latest'
-      # Feature tests in examples
-      - name: Test crd_derive_no_schema example
-        run: cargo test -p kube-examples --example crd_derive_no_schema --no-default-features --features=openssl-tls,latest
-        if: matrix.os == 'ubuntu-latest'
 
   msrv:
     # Run `cargo check` on our minimum supported Rust version
@@ -150,8 +146,6 @@ jobs:
       # Run the equivalent of `just integration`
       - name: Run all integration library tests
         run: cargo test --lib --workspace --exclude e2e --all-features -- --ignored
-      - name: Run all integration doc tests
-        run: cargo test --doc --workspace --exclude e2e --all-features -- --ignored
       - name: Run crd example tests
         run: cargo run -p kube-examples --example crd_api
       - name: Run derive example tests
