Add a VS Code devcontainer configuration (#788)
* Add a VS Code devcontainer configuration

When loading `kube-rs` in VS Code, a variety of configurations are
needed to end up with a working environment. It does't Just Work out of
the box.

VS Code [devcontainers][dc] make it easy to bootstrap a development
environment with project-specific tooling and configuration. This
configuration should also be usable in [GitHub Codespaces][ghcs].

This configuration ensures that various tools are available including:

* `cargo-deny`
* `cargo-tarpaulin`
* `k3d`
* `kubectl`
* rust stable-1.58 toolchain
* rust nightly toolchain
* a variety of related VS Code plugins

While this developer image is based on rust 1.56 (the documented MSRV
for the project), it updates the default toolchain to be _nightly_ so
clippy and rustfmt work as expected (since `kube-rs` depends on nightly
versions of these tools).

[dc]: https://code.visualstudio.com/docs/remote/containers
[ghcs]: https://github.com/features/codespaces

Signed-off-by: Oliver Gould <ver@buoyant.io>

* Fix typo in readme

Co-authored-by: Eirik A <sszynrae@gmail.com>
Signed-off-by: Oliver Gould <ver@buoyant.io>

* update k8s-openapi to 0.14.0 (#789)

removing instructions on default features since they are all turned off
by default.

Signed-off-by: clux <sszynrae@gmail.com>
Signed-off-by: Oliver Gould <ver@buoyant.io>

* release 0.67.0

Signed-off-by: Oliver Gould <ver@buoyant.io>

* import changelog for 0.67

Signed-off-by: clux <sszynrae@gmail.com>
Signed-off-by: Oliver Gould <ver@buoyant.io>

* Fix/cleanup devcontainer dockerfile

Signed-off-by: Oliver Gould <ver@buoyant.io>

* Add jq

Signed-off-by: Oliver Gould <ver@buoyant.io>

* Add an `scurl` utility script to cut down on verbose curl flags in Dockerfile

Signed-off-by: Oliver Gould <ver@buoyant.io>

* Re-add lldb extension

Signed-off-by: Oliver Gould <ver@buoyant.io>

* Add usage to devcontainer readme

Signed-off-by: Oliver Gould <ver@buoyant.io>

* Add a devcontainer MSRV check to CI

Signed-off-by: Oliver Gould <ver@buoyant.io>

* Add a devcontainer CI workflow

Ensures that the devcontainer builds when the configuration changes.

Signed-off-by: Oliver Gould <ver@buoyant.io>

* debug ci.yml

Signed-off-by: Oliver Gould <ver@buoyant.io>

* Fix MSRV check action to work with "set -e"

Signed-off-by: Oliver Gould <ver@buoyant.io>

* test MSRV mismatch

Signed-off-by: Oliver Gould <ver@buoyant.io>

* Restore MSRV devcontainer version

Signed-off-by: Oliver Gould <ver@buoyant.io>

* fix devcontainer workflow

Signed-off-by: Oliver Gould <ver@buoyant.io>

Co-authored-by: Eirik A <sszynrae@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -91,6 +91,17 @@ jobs:
         command: check
         args: --all
 
+    - name: Check devcontainer matches MSRV
+      run: |
+        versions=$(sed -nE 's|^FROM (.*/)?rust:([^ ]+)|\2|p' .devcontainer/Dockerfile)
+        echo "Versions: $versions"
+        mismatches=$(echo "$versions" | grep -v '^${{ steps.msrv.outputs.msrv }}' || true)
+        echo "Mismatches: $mismatches"
+        if [ -n "$mismatches" ]; then
+          echo "::error ::Devcontainer includes incorrect rust version(s): $mismatches"
+          exit 1
+        fi
+
   e2e:
     # e2e tests are docker on linux
     runs-on: ubuntu-latest
